export interface Player {
  id: string;
  name: string;
  position: 'QB' | 'RB' | 'WR' | 'TE' | 'K' | 'DEF';
  team: string;
  isDrafted: boolean;
  draftedBy?: string;
  draftPick?: number;
}

export type RosterEntry = Omit<Player, 'isDrafted' | 'draftedBy' | 'draftPick'>;

// Grouped by team so rosters are easy to scan and edit.
// Depth charts as of 2026-08-15 (NFL preseason) — QB/TE 2 deep, RB 3 deep, WR 4 deep,
// 1 kicker, and a single DEF entry representing each team's defense as a unit.
//
// Preseason caveat: rosters are still being finalized (cuts to 53 happen late August),
// so several slots — especially WR3/4, RB2/3, and a few contested QB battles — are fluid
// and worth re-checking after final roster cuts.
//
// TODO: Foster Moreau was returned as TE2 for both HOU and NO by independent research
// passes — he can only be on one roster. Verify and remove from the wrong team.
export const NFL_PLAYERS_BY_TEAM: Record<string, RosterEntry[]> = {
  ARI: [
    { id: 'ARI-QB1', name: 'Jacoby Brissett', position: 'QB', team: 'ARI' },
    { id: 'ARI-QB2', name: 'Gardner Minshew II', position: 'QB', team: 'ARI' },
    { id: 'ARI-RB1', name: 'Jeremiyah Love', position: 'RB', team: 'ARI' },
    { id: 'ARI-RB2', name: 'Tyler Allgeier', position: 'RB', team: 'ARI' },
    { id: 'ARI-RB3', name: 'James Conner', position: 'RB', team: 'ARI' },
    { id: 'ARI-WR1', name: 'Marvin Harrison Jr.', position: 'WR', team: 'ARI' },
    { id: 'ARI-WR2', name: 'Michael Wilson', position: 'WR', team: 'ARI' },
    { id: 'ARI-WR3', name: 'Kendrick Bourne', position: 'WR', team: 'ARI' },
    { id: 'ARI-WR4', name: 'Xavier Weaver', position: 'WR', team: 'ARI' },
    { id: 'ARI-TE1', name: 'Trey McBride', position: 'TE', team: 'ARI' },
    { id: 'ARI-TE2', name: 'Elijah Higgins', position: 'TE', team: 'ARI' },
    { id: 'ARI-K1', name: 'Chad Ryland', position: 'K', team: 'ARI' },
    { id: 'ARI-DEF', name: 'Arizona Cardinals Defense', position: 'DEF', team: 'ARI' },
  ],
  ATL: [
    { id: 'ATL-QB1', name: 'Tua Tagovailoa', position: 'QB', team: 'ATL' },
    { id: 'ATL-QB2', name: 'Cooper Rush', position: 'QB', team: 'ATL' },
    { id: 'ATL-RB1', name: 'Bijan Robinson', position: 'RB', team: 'ATL' },
    { id: 'ATL-RB2', name: 'Brian Robinson Jr.', position: 'RB', team: 'ATL' },
    { id: 'ATL-RB3', name: 'Tyler Goodson', position: 'RB', team: 'ATL' },
    { id: 'ATL-WR1', name: 'Drake London', position: 'WR', team: 'ATL' },
    { id: 'ATL-WR2', name: 'Jahan Dotson', position: 'WR', team: 'ATL' },
    { id: 'ATL-WR3', name: 'Olamide Zaccheaus', position: 'WR', team: 'ATL' },
    { id: 'ATL-WR4', name: 'Zachariah Branch', position: 'WR', team: 'ATL' },
    { id: 'ATL-TE1', name: 'Kyle Pitts Sr.', position: 'TE', team: 'ATL' },
    { id: 'ATL-TE2', name: 'Charlie Woerner', position: 'TE', team: 'ATL' },
    { id: 'ATL-K1', name: 'Nick Folk', position: 'K', team: 'ATL' },
    { id: 'ATL-DEF', name: 'Atlanta Falcons Defense', position: 'DEF', team: 'ATL' },
  ],
  BAL: [
    { id: 'BAL-QB1', name: 'Lamar Jackson', position: 'QB', team: 'BAL' },
    { id: 'BAL-QB2', name: 'Tyler Huntley', position: 'QB', team: 'BAL' },
    { id: 'BAL-RB1', name: 'Derrick Henry', position: 'RB', team: 'BAL' },
    { id: 'BAL-RB2', name: 'Justice Hill', position: 'RB', team: 'BAL' },
    { id: 'BAL-RB3', name: 'Rasheen Ali', position: 'RB', team: 'BAL' },
    { id: 'BAL-WR1', name: 'Zay Flowers', position: 'WR', team: 'BAL' },
    { id: 'BAL-WR2', name: 'Rashod Bateman', position: 'WR', team: 'BAL' },
    { id: 'BAL-WR3', name: 'Devontez Walker', position: 'WR', team: 'BAL' },
    { id: 'BAL-WR4', name: 'Chris Moore', position: 'WR', team: 'BAL' },
    { id: 'BAL-TE1', name: 'Mark Andrews', position: 'TE', team: 'BAL' },
    { id: 'BAL-TE2', name: 'Durham Smythe', position: 'TE', team: 'BAL' },
    { id: 'BAL-K1', name: 'Tyler Loop', position: 'K', team: 'BAL' },
    { id: 'BAL-DEF', name: 'Baltimore Ravens Defense', position: 'DEF', team: 'BAL' },
  ],
  BUF: [
    { id: 'BUF-QB1', name: 'Josh Allen', position: 'QB', team: 'BUF' },
    { id: 'BUF-QB2', name: 'Kyle Allen', position: 'QB', team: 'BUF' },
    { id: 'BUF-RB1', name: 'James Cook III', position: 'RB', team: 'BUF' },
    { id: 'BUF-RB2', name: 'Ray Davis', position: 'RB', team: 'BUF' },
    { id: 'BUF-RB3', name: 'Ty Johnson', position: 'RB', team: 'BUF' },
    { id: 'BUF-WR1', name: 'DJ Moore', position: 'WR', team: 'BUF' },
    { id: 'BUF-WR2', name: 'Khalil Shakir', position: 'WR', team: 'BUF' },
    { id: 'BUF-WR3', name: 'Keon Coleman', position: 'WR', team: 'BUF' },
    { id: 'BUF-WR4', name: 'Joshua Palmer', position: 'WR', team: 'BUF' },
    { id: 'BUF-TE1', name: 'Dalton Kincaid', position: 'TE', team: 'BUF' },
    { id: 'BUF-TE2', name: 'Dawson Knox', position: 'TE', team: 'BUF' },
    { id: 'BUF-K1', name: 'Tyler Bass', position: 'K', team: 'BUF' },
    { id: 'BUF-DEF', name: 'Buffalo Bills Defense', position: 'DEF', team: 'BUF' },
  ],
  CAR: [
    { id: 'CAR-QB1', name: 'Bryce Young', position: 'QB', team: 'CAR' },
    { id: 'CAR-QB2', name: 'Kenny Pickett', position: 'QB', team: 'CAR' },
    { id: 'CAR-RB1', name: 'Chuba Hubbard', position: 'RB', team: 'CAR' },
    { id: 'CAR-RB2', name: 'Jonathon Brooks', position: 'RB', team: 'CAR' },
    { id: 'CAR-RB3', name: 'Trevor Etienne', position: 'RB', team: 'CAR' },
    { id: 'CAR-WR1', name: 'Tetairoa McMillan', position: 'WR', team: 'CAR' },
    { id: 'CAR-WR2', name: 'Xavier Legette', position: 'WR', team: 'CAR' },
    { id: 'CAR-WR3', name: 'Jalen Coker', position: 'WR', team: 'CAR' },
    { id: 'CAR-WR4', name: 'Hunter Renfrow', position: 'WR', team: 'CAR' },
    { id: 'CAR-TE1', name: 'Tommy Tremble', position: 'TE', team: 'CAR' },
    { id: 'CAR-TE2', name: "Ja'Tavion Sanders", position: 'TE', team: 'CAR' },
    { id: 'CAR-K1', name: 'Ryan Fitzgerald', position: 'K', team: 'CAR' },
    { id: 'CAR-DEF', name: 'Carolina Panthers Defense', position: 'DEF', team: 'CAR' },
  ],
  CHI: [
    { id: 'CHI-QB1', name: 'Caleb Williams', position: 'QB', team: 'CHI' },
    { id: 'CHI-QB2', name: 'Tyson Bagent', position: 'QB', team: 'CHI' },
    { id: 'CHI-RB1', name: "D'Andre Swift", position: 'RB', team: 'CHI' },
    { id: 'CHI-RB2', name: 'Kyle Monangai', position: 'RB', team: 'CHI' },
    { id: 'CHI-RB3', name: 'Roschon Johnson', position: 'RB', team: 'CHI' },
    { id: 'CHI-WR1', name: 'Rome Odunze', position: 'WR', team: 'CHI' },
    { id: 'CHI-WR2', name: 'Luther Burden III', position: 'WR', team: 'CHI' },
    { id: 'CHI-WR3', name: 'Kalif Raymond', position: 'WR', team: 'CHI' },
    { id: 'CHI-WR4', name: 'Scotty Miller', position: 'WR', team: 'CHI' },
    { id: 'CHI-TE1', name: 'Colston Loveland', position: 'TE', team: 'CHI' },
    { id: 'CHI-TE2', name: 'Cole Kmet', position: 'TE', team: 'CHI' },
    { id: 'CHI-K1', name: 'Cairo Santos', position: 'K', team: 'CHI' },
    { id: 'CHI-DEF', name: 'Chicago Bears Defense', position: 'DEF', team: 'CHI' },
  ],
  CIN: [
    { id: 'CIN-QB1', name: 'Joe Burrow', position: 'QB', team: 'CIN' },
    { id: 'CIN-QB2', name: 'Joe Flacco', position: 'QB', team: 'CIN' },
    { id: 'CIN-RB1', name: 'Chase Brown', position: 'RB', team: 'CIN' },
    { id: 'CIN-RB2', name: 'Samaje Perine', position: 'RB', team: 'CIN' },
    { id: 'CIN-RB3', name: 'Tahj Brooks', position: 'RB', team: 'CIN' },
    { id: 'CIN-WR1', name: "Ja'Marr Chase", position: 'WR', team: 'CIN' },
    { id: 'CIN-WR2', name: 'Tee Higgins', position: 'WR', team: 'CIN' },
    { id: 'CIN-WR3', name: 'Andrei Iosivas', position: 'WR', team: 'CIN' },
    { id: 'CIN-WR4', name: 'Charlie Jones', position: 'WR', team: 'CIN' },
    { id: 'CIN-TE1', name: 'Mike Gesicki', position: 'TE', team: 'CIN' },
    { id: 'CIN-TE2', name: 'Drew Sample', position: 'TE', team: 'CIN' },
    { id: 'CIN-K1', name: 'Evan McPherson', position: 'K', team: 'CIN' },
    { id: 'CIN-DEF', name: 'Cincinnati Bengals Defense', position: 'DEF', team: 'CIN' },
  ],
  CLE: [
    // QB1/QB2 order is a genuine, unsettled camp battle as of 2026-08-15 (Watson started
    // preseason G1, Sanders slated for G2) — treat as fluid.
    { id: 'CLE-QB1', name: 'Deshaun Watson', position: 'QB', team: 'CLE' },
    { id: 'CLE-QB2', name: 'Shedeur Sanders', position: 'QB', team: 'CLE' },
    { id: 'CLE-RB1', name: 'Quinshon Judkins', position: 'RB', team: 'CLE' },
    { id: 'CLE-RB2', name: 'Dylan Sampson', position: 'RB', team: 'CLE' },
    { id: 'CLE-RB3', name: 'Raheim Sanders', position: 'RB', team: 'CLE' },
    { id: 'CLE-WR1', name: 'Jerry Jeudy', position: 'WR', team: 'CLE' },
    { id: 'CLE-WR2', name: 'Denzel Boston', position: 'WR', team: 'CLE' },
    { id: 'CLE-WR3', name: 'KC Concepcion', position: 'WR', team: 'CLE' },
    { id: 'CLE-WR4', name: 'Cedric Tillman', position: 'WR', team: 'CLE' },
    { id: 'CLE-TE1', name: 'Harold Fannin Jr.', position: 'TE', team: 'CLE' },
    { id: 'CLE-TE2', name: 'Blake Whiteheart', position: 'TE', team: 'CLE' },
    { id: 'CLE-K1', name: 'Andre Szmyt', position: 'K', team: 'CLE' },
    { id: 'CLE-DEF', name: 'Cleveland Browns Defense', position: 'DEF', team: 'CLE' },
  ],
  DAL: [
    { id: 'DAL-QB1', name: 'Dak Prescott', position: 'QB', team: 'DAL' },
    { id: 'DAL-QB2', name: 'Joe Milton III', position: 'QB', team: 'DAL' },
    { id: 'DAL-RB1', name: 'Javonte Williams', position: 'RB', team: 'DAL' },
    { id: 'DAL-RB2', name: 'Jaydon Blue', position: 'RB', team: 'DAL' },
    { id: 'DAL-RB3', name: 'Phil Mafah', position: 'RB', team: 'DAL' },
    { id: 'DAL-WR1', name: 'CeeDee Lamb', position: 'WR', team: 'DAL' },
    { id: 'DAL-WR2', name: 'George Pickens', position: 'WR', team: 'DAL' },
    { id: 'DAL-WR3', name: 'Ryan Flournoy', position: 'WR', team: 'DAL' },
    { id: 'DAL-WR4', name: 'KaVontae Turpin', position: 'WR', team: 'DAL' },
    { id: 'DAL-TE1', name: 'Jake Ferguson', position: 'TE', team: 'DAL' },
    { id: 'DAL-TE2', name: 'Brevyn Spann-Ford', position: 'TE', team: 'DAL' },
    { id: 'DAL-K1', name: 'Brandon Aubrey', position: 'K', team: 'DAL' },
    { id: 'DAL-DEF', name: 'Dallas Cowboys Defense', position: 'DEF', team: 'DAL' },
  ],
  DEN: [
    { id: 'DEN-QB1', name: 'Bo Nix', position: 'QB', team: 'DEN' },
    { id: 'DEN-QB2', name: 'Jarrett Stidham', position: 'QB', team: 'DEN' },
    { id: 'DEN-RB1', name: 'J.K. Dobbins', position: 'RB', team: 'DEN' },
    { id: 'DEN-RB2', name: 'RJ Harvey', position: 'RB', team: 'DEN' },
    { id: 'DEN-RB3', name: 'Jonah Coleman', position: 'RB', team: 'DEN' },
    { id: 'DEN-WR1', name: 'Courtland Sutton', position: 'WR', team: 'DEN' },
    { id: 'DEN-WR2', name: 'Jaylen Waddle', position: 'WR', team: 'DEN' },
    { id: 'DEN-WR3', name: 'Troy Franklin', position: 'WR', team: 'DEN' },
    { id: 'DEN-WR4', name: 'Marvin Mims Jr.', position: 'WR', team: 'DEN' },
    { id: 'DEN-TE1', name: 'Evan Engram', position: 'TE', team: 'DEN' },
    { id: 'DEN-TE2', name: 'Adam Trautman', position: 'TE', team: 'DEN' },
    { id: 'DEN-K1', name: 'Wil Lutz', position: 'K', team: 'DEN' },
    { id: 'DEN-DEF', name: 'Denver Broncos Defense', position: 'DEF', team: 'DEN' },
  ],
  DET: [
    { id: 'DET-QB1', name: 'Jared Goff', position: 'QB', team: 'DET' },
    { id: 'DET-QB2', name: 'Joshua Dobbs', position: 'QB', team: 'DET' },
    { id: 'DET-RB1', name: 'Jahmyr Gibbs', position: 'RB', team: 'DET' },
    { id: 'DET-RB2', name: 'Isiah Pacheco', position: 'RB', team: 'DET' },
    { id: 'DET-RB3', name: 'Sione Vaki', position: 'RB', team: 'DET' },
    { id: 'DET-WR1', name: 'Amon-Ra St. Brown', position: 'WR', team: 'DET' },
    { id: 'DET-WR2', name: 'Jameson Williams', position: 'WR', team: 'DET' },
    { id: 'DET-WR3', name: 'Isaac TeSlaa', position: 'WR', team: 'DET' },
    { id: 'DET-WR4', name: 'Greg Dortch', position: 'WR', team: 'DET' },
    { id: 'DET-TE1', name: 'Sam LaPorta', position: 'TE', team: 'DET' },
    { id: 'DET-TE2', name: 'Brock Wright', position: 'TE', team: 'DET' },
    { id: 'DET-K1', name: 'Jake Bates', position: 'K', team: 'DET' },
    { id: 'DET-DEF', name: 'Detroit Lions Defense', position: 'DEF', team: 'DET' },
  ],
  GB: [
    { id: 'GB-QB1', name: 'Jordan Love', position: 'QB', team: 'GB' },
    { id: 'GB-QB2', name: 'Tyrod Taylor', position: 'QB', team: 'GB' },
    { id: 'GB-RB1', name: 'Josh Jacobs', position: 'RB', team: 'GB' },
    { id: 'GB-RB2', name: 'MarShawn Lloyd', position: 'RB', team: 'GB' },
    { id: 'GB-RB3', name: 'Chris Brooks', position: 'RB', team: 'GB' },
    { id: 'GB-WR1', name: 'Christian Watson', position: 'WR', team: 'GB' },
    { id: 'GB-WR2', name: 'Jayden Reed', position: 'WR', team: 'GB' },
    { id: 'GB-WR3', name: 'Matthew Golden', position: 'WR', team: 'GB' },
    { id: 'GB-WR4', name: 'Savion Williams', position: 'WR', team: 'GB' },
    { id: 'GB-TE1', name: 'Tucker Kraft', position: 'TE', team: 'GB' },
    { id: 'GB-TE2', name: 'Josh Whyle', position: 'TE', team: 'GB' },
    { id: 'GB-K1', name: 'Trey Smack', position: 'K', team: 'GB' },
    { id: 'GB-DEF', name: 'Green Bay Packers Defense', position: 'DEF', team: 'GB' },
  ],
  HOU: [
    { id: 'HOU-QB1', name: 'C.J. Stroud', position: 'QB', team: 'HOU' },
    { id: 'HOU-QB2', name: 'Davis Mills', position: 'QB', team: 'HOU' },
    { id: 'HOU-RB1', name: 'David Montgomery', position: 'RB', team: 'HOU' },
    { id: 'HOU-RB2', name: 'Woody Marks', position: 'RB', team: 'HOU' },
    { id: 'HOU-RB3', name: 'Jawhar Jordan', position: 'RB', team: 'HOU' },
    { id: 'HOU-WR1', name: 'Nico Collins', position: 'WR', team: 'HOU' },
    { id: 'HOU-WR2', name: 'Jayden Higgins', position: 'WR', team: 'HOU' },
    { id: 'HOU-WR3', name: 'Jaylin Noel', position: 'WR', team: 'HOU' },
    { id: 'HOU-WR4', name: 'Tank Dell', position: 'WR', team: 'HOU' },
    { id: 'HOU-TE1', name: 'Dalton Schultz', position: 'TE', team: 'HOU' },
    // See TODO above: Foster Moreau conflicts with NO-TE2, verify which team is correct.
    { id: 'HOU-TE2', name: 'Foster Moreau', position: 'TE', team: 'HOU' },
    { id: 'HOU-K1', name: "Ka'imi Fairbairn", position: 'K', team: 'HOU' },
    { id: 'HOU-DEF', name: 'Houston Texans Defense', position: 'DEF', team: 'HOU' },
  ],
  IND: [
    { id: 'IND-QB1', name: 'Daniel Jones', position: 'QB', team: 'IND' },
    { id: 'IND-QB2', name: 'Anthony Richardson Sr.', position: 'QB', team: 'IND' },
    { id: 'IND-RB1', name: 'Jonathan Taylor', position: 'RB', team: 'IND' },
    { id: 'IND-RB2', name: 'DJ Giddens', position: 'RB', team: 'IND' },
    { id: 'IND-RB3', name: 'Seth McGowan', position: 'RB', team: 'IND' },
    { id: 'IND-WR1', name: 'Alec Pierce', position: 'WR', team: 'IND' },
    { id: 'IND-WR2', name: 'Josh Downs', position: 'WR', team: 'IND' },
    { id: 'IND-WR3', name: 'Ashton Dulin', position: 'WR', team: 'IND' },
    { id: 'IND-WR4', name: 'Nick Westbrook-Ikhine', position: 'WR', team: 'IND' },
    { id: 'IND-TE1', name: 'Tyler Warren', position: 'TE', team: 'IND' },
    { id: 'IND-TE2', name: 'Mo Alie-Cox', position: 'TE', team: 'IND' },
    { id: 'IND-K1', name: 'Blake Grupe', position: 'K', team: 'IND' },
    { id: 'IND-DEF', name: 'Indianapolis Colts Defense', position: 'DEF', team: 'IND' },
  ],
  JAX: [
    { id: 'JAX-QB1', name: 'Trevor Lawrence', position: 'QB', team: 'JAX' },
    { id: 'JAX-QB2', name: 'Nick Mullens', position: 'QB', team: 'JAX' },
    { id: 'JAX-RB1', name: 'Bhayshul Tuten', position: 'RB', team: 'JAX' },
    { id: 'JAX-RB2', name: 'Chris Rodriguez Jr.', position: 'RB', team: 'JAX' },
    { id: 'JAX-RB3', name: 'LeQuint Allen Jr.', position: 'RB', team: 'JAX' },
    { id: 'JAX-WR1', name: 'Brian Thomas Jr.', position: 'WR', team: 'JAX' },
    { id: 'JAX-WR2', name: 'Jakobi Meyers', position: 'WR', team: 'JAX' },
    { id: 'JAX-WR3', name: 'Parker Washington', position: 'WR', team: 'JAX' },
    { id: 'JAX-WR4', name: 'Travis Hunter', position: 'WR', team: 'JAX' },
    { id: 'JAX-TE1', name: 'Brenton Strange', position: 'TE', team: 'JAX' },
    { id: 'JAX-TE2', name: 'Nate Boerkircher', position: 'TE', team: 'JAX' },
    { id: 'JAX-K1', name: 'Cam Little', position: 'K', team: 'JAX' },
    { id: 'JAX-DEF', name: 'Jacksonville Jaguars Defense', position: 'DEF', team: 'JAX' },
  ],
  KC: [
    { id: 'KC-QB1', name: 'Patrick Mahomes', position: 'QB', team: 'KC' },
    { id: 'KC-QB2', name: 'Justin Fields', position: 'QB', team: 'KC' },
    { id: 'KC-RB1', name: 'Kenneth Walker III', position: 'RB', team: 'KC' },
    { id: 'KC-RB2', name: 'Emari Demercado', position: 'RB', team: 'KC' },
    { id: 'KC-RB3', name: 'Emmett Johnson', position: 'RB', team: 'KC' },
    { id: 'KC-WR1', name: 'Rashee Rice', position: 'WR', team: 'KC' },
    { id: 'KC-WR2', name: 'Xavier Worthy', position: 'WR', team: 'KC' },
    { id: 'KC-WR3', name: 'Tyquan Thornton', position: 'WR', team: 'KC' },
    { id: 'KC-WR4', name: 'Jalen Royals', position: 'WR', team: 'KC' },
    { id: 'KC-TE1', name: 'Travis Kelce', position: 'TE', team: 'KC' },
    { id: 'KC-TE2', name: 'Noah Gray', position: 'TE', team: 'KC' },
    { id: 'KC-K1', name: 'Harrison Butker', position: 'K', team: 'KC' },
    { id: 'KC-DEF', name: 'Kansas City Chiefs Defense', position: 'DEF', team: 'KC' },
  ],
  LAC: [
    { id: 'LAC-QB1', name: 'Justin Herbert', position: 'QB', team: 'LAC' },
    { id: 'LAC-QB2', name: 'Trey Lance', position: 'QB', team: 'LAC' },
    { id: 'LAC-RB1', name: 'Omarion Hampton', position: 'RB', team: 'LAC' },
    { id: 'LAC-RB2', name: 'Kimani Vidal', position: 'RB', team: 'LAC' },
    { id: 'LAC-RB3', name: 'Keaton Mitchell', position: 'RB', team: 'LAC' },
    { id: 'LAC-WR1', name: 'Ladd McConkey', position: 'WR', team: 'LAC' },
    { id: 'LAC-WR2', name: 'Quentin Johnston', position: 'WR', team: 'LAC' },
    { id: 'LAC-WR3', name: "Tre' Harris", position: 'WR', team: 'LAC' },
    { id: 'LAC-WR4', name: 'Brenen Thompson', position: 'WR', team: 'LAC' },
    { id: 'LAC-TE1', name: 'Oronde Gadsden II', position: 'TE', team: 'LAC' },
    { id: 'LAC-TE2', name: 'David Njoku', position: 'TE', team: 'LAC' },
    { id: 'LAC-K1', name: 'Cameron Dicker', position: 'K', team: 'LAC' },
    { id: 'LAC-DEF', name: 'Los Angeles Chargers Defense', position: 'DEF', team: 'LAC' },
  ],
  LV: [
    { id: 'LV-QB1', name: 'Kirk Cousins', position: 'QB', team: 'LV' },
    { id: 'LV-QB2', name: 'Fernando Mendoza', position: 'QB', team: 'LV' },
    { id: 'LV-RB1', name: 'Ashton Jeanty', position: 'RB', team: 'LV' },
    { id: 'LV-RB2', name: 'Mike Washington Jr.', position: 'RB', team: 'LV' },
    { id: 'LV-RB3', name: 'Dylan Laube', position: 'RB', team: 'LV' },
    { id: 'LV-WR1', name: 'Tre Tucker', position: 'WR', team: 'LV' },
    { id: 'LV-WR2', name: "Dont'e Thornton Jr.", position: 'WR', team: 'LV' },
    { id: 'LV-WR3', name: 'Jalen Nailor', position: 'WR', team: 'LV' },
    { id: 'LV-WR4', name: 'Jack Bech', position: 'WR', team: 'LV' },
    { id: 'LV-TE1', name: 'Brock Bowers', position: 'TE', team: 'LV' },
    { id: 'LV-TE2', name: 'Michael Mayer', position: 'TE', team: 'LV' },
    { id: 'LV-K1', name: 'Matt Gay', position: 'K', team: 'LV' },
    { id: 'LV-DEF', name: 'Las Vegas Raiders Defense', position: 'DEF', team: 'LV' },
  ],
  LAR: [
    { id: 'LAR-QB1', name: 'Matthew Stafford', position: 'QB', team: 'LAR' },
    { id: 'LAR-QB2', name: 'Stetson Bennett IV', position: 'QB', team: 'LAR' },
    { id: 'LAR-RB1', name: 'Kyren Williams', position: 'RB', team: 'LAR' },
    { id: 'LAR-RB2', name: 'Blake Corum', position: 'RB', team: 'LAR' },
    { id: 'LAR-RB3', name: 'Ronnie Rivers', position: 'RB', team: 'LAR' },
    { id: 'LAR-WR1', name: 'Puka Nacua', position: 'WR', team: 'LAR' },
    { id: 'LAR-WR2', name: 'Davante Adams', position: 'WR', team: 'LAR' },
    { id: 'LAR-WR3', name: 'Jordan Whittington', position: 'WR', team: 'LAR' },
    { id: 'LAR-WR4', name: 'Konata Mumpfield', position: 'WR', team: 'LAR' },
    { id: 'LAR-TE1', name: 'Colby Parkinson', position: 'TE', team: 'LAR' },
    { id: 'LAR-TE2', name: 'Tyler Higbee', position: 'TE', team: 'LAR' },
    { id: 'LAR-K1', name: 'Harrison Mevis', position: 'K', team: 'LAR' },
    { id: 'LAR-DEF', name: 'Los Angeles Rams Defense', position: 'DEF', team: 'LAR' },
  ],
  MIA: [
    { id: 'MIA-QB1', name: 'Malik Willis', position: 'QB', team: 'MIA' },
    { id: 'MIA-QB2', name: 'Quinn Ewers', position: 'QB', team: 'MIA' },
    { id: 'MIA-RB1', name: "De'Von Achane", position: 'RB', team: 'MIA' },
    { id: 'MIA-RB2', name: 'Jaylen Wright', position: 'RB', team: 'MIA' },
    { id: 'MIA-RB3', name: 'Ollie Gordon II', position: 'RB', team: 'MIA' },
    { id: 'MIA-WR1', name: 'Malik Washington', position: 'WR', team: 'MIA' },
    { id: 'MIA-WR2', name: 'Jalen Tolbert', position: 'WR', team: 'MIA' },
    { id: 'MIA-WR3', name: 'Caleb Douglas', position: 'WR', team: 'MIA' },
    { id: 'MIA-WR4', name: 'Tutu Atwell', position: 'WR', team: 'MIA' },
    { id: 'MIA-TE1', name: 'Greg Dulcich', position: 'TE', team: 'MIA' },
    { id: 'MIA-TE2', name: 'Will Kacmarek', position: 'TE', team: 'MIA' },
    { id: 'MIA-K1', name: 'Riley Patterson', position: 'K', team: 'MIA' },
    { id: 'MIA-DEF', name: 'Miami Dolphins Defense', position: 'DEF', team: 'MIA' },
  ],
  MIN: [
    { id: 'MIN-QB1', name: 'Kyler Murray', position: 'QB', team: 'MIN' },
    { id: 'MIN-QB2', name: 'J.J. McCarthy', position: 'QB', team: 'MIN' },
    { id: 'MIN-RB1', name: 'Aaron Jones Sr.', position: 'RB', team: 'MIN' },
    { id: 'MIN-RB2', name: 'Jordan Mason', position: 'RB', team: 'MIN' },
    { id: 'MIN-RB3', name: 'Zavier Scott', position: 'RB', team: 'MIN' },
    { id: 'MIN-WR1', name: 'Justin Jefferson', position: 'WR', team: 'MIN' },
    { id: 'MIN-WR2', name: 'Jordan Addison', position: 'WR', team: 'MIN' },
    // Only 3 fantasy-relevant WRs confirmed; WR4 was unsettled per sources at fetch time.
    { id: 'MIN-WR3', name: 'Jauan Jennings', position: 'WR', team: 'MIN' },
    { id: 'MIN-TE1', name: 'T.J. Hockenson', position: 'TE', team: 'MIN' },
    { id: 'MIN-TE2', name: 'Josh Oliver', position: 'TE', team: 'MIN' },
    { id: 'MIN-K1', name: 'Will Reichard', position: 'K', team: 'MIN' },
    { id: 'MIN-DEF', name: 'Minnesota Vikings Defense', position: 'DEF', team: 'MIN' },
  ],
  NE: [
    { id: 'NE-QB1', name: 'Drake Maye', position: 'QB', team: 'NE' },
    { id: 'NE-QB2', name: 'Tommy DeVito', position: 'QB', team: 'NE' },
    { id: 'NE-RB1', name: 'Rhamondre Stevenson', position: 'RB', team: 'NE' },
    { id: 'NE-RB2', name: 'TreVeyon Henderson', position: 'RB', team: 'NE' },
    { id: 'NE-RB3', name: 'Lan Larison', position: 'RB', team: 'NE' },
    { id: 'NE-WR1', name: 'A.J. Brown', position: 'WR', team: 'NE' },
    { id: 'NE-WR2', name: 'Romeo Doubs', position: 'WR', team: 'NE' },
    { id: 'NE-WR3', name: 'DeMario Douglas', position: 'WR', team: 'NE' },
    { id: 'NE-WR4', name: 'Kayshon Boutte', position: 'WR', team: 'NE' },
    { id: 'NE-TE1', name: 'Hunter Henry', position: 'TE', team: 'NE' },
    { id: 'NE-TE2', name: 'Eli Raridon', position: 'TE', team: 'NE' },
    { id: 'NE-K1', name: 'Andy Borregales', position: 'K', team: 'NE' },
    { id: 'NE-DEF', name: 'New England Patriots Defense', position: 'DEF', team: 'NE' },
  ],
  NO: [
    { id: 'NO-QB1', name: 'Tyler Shough', position: 'QB', team: 'NO' },
    { id: 'NO-QB2', name: 'Spencer Rattler', position: 'QB', team: 'NO' },
    { id: 'NO-RB1', name: 'Alvin Kamara', position: 'RB', team: 'NO' },
    { id: 'NO-RB2', name: 'Travis Etienne Jr.', position: 'RB', team: 'NO' },
    { id: 'NO-RB3', name: 'Devin Neal', position: 'RB', team: 'NO' },
    { id: 'NO-WR1', name: 'Chris Olave', position: 'WR', team: 'NO' },
    { id: 'NO-WR2', name: 'Jordyn Tyson', position: 'WR', team: 'NO' },
    { id: 'NO-WR3', name: 'Devaughn Vele', position: 'WR', team: 'NO' },
    { id: 'NO-WR4', name: 'Mason Tipton', position: 'WR', team: 'NO' },
    { id: 'NO-TE1', name: 'Juwan Johnson', position: 'TE', team: 'NO' },
    // See TODO above: Foster Moreau conflicts with HOU-TE2, verify which team is correct.
    { id: 'NO-TE2', name: 'Foster Moreau', position: 'TE', team: 'NO' },
    { id: 'NO-K1', name: 'Charlie Smyth', position: 'K', team: 'NO' },
    { id: 'NO-DEF', name: 'New Orleans Saints Defense', position: 'DEF', team: 'NO' },
  ],
  NYG: [
    { id: 'NYG-QB1', name: 'Jaxson Dart', position: 'QB', team: 'NYG' },
    { id: 'NYG-QB2', name: 'Jameis Winston', position: 'QB', team: 'NYG' },
    { id: 'NYG-RB1', name: 'Cam Skattebo', position: 'RB', team: 'NYG' },
    { id: 'NYG-RB2', name: 'Tyrone Tracy Jr.', position: 'RB', team: 'NYG' },
    { id: 'NYG-RB3', name: 'Devin Singletary', position: 'RB', team: 'NYG' },
    { id: 'NYG-WR1', name: 'Malik Nabers', position: 'WR', team: 'NYG' },
    { id: 'NYG-WR2', name: 'Darius Slayton', position: 'WR', team: 'NYG' },
    { id: 'NYG-WR3', name: 'Darnell Mooney', position: 'WR', team: 'NYG' },
    { id: 'NYG-WR4', name: 'Calvin Austin III', position: 'WR', team: 'NYG' },
    { id: 'NYG-TE1', name: 'Isaiah Likely', position: 'TE', team: 'NYG' },
    { id: 'NYG-TE2', name: 'Theo Johnson', position: 'TE', team: 'NYG' },
    { id: 'NYG-K1', name: 'Ben Sauls', position: 'K', team: 'NYG' },
    { id: 'NYG-DEF', name: 'New York Giants Defense', position: 'DEF', team: 'NYG' },
  ],
  NYJ: [
    { id: 'NYJ-QB1', name: 'Geno Smith', position: 'QB', team: 'NYJ' },
    { id: 'NYJ-QB2', name: 'Cade Klubnik', position: 'QB', team: 'NYJ' },
    { id: 'NYJ-RB1', name: 'Breece Hall', position: 'RB', team: 'NYJ' },
    { id: 'NYJ-RB2', name: 'Braelon Allen', position: 'RB', team: 'NYJ' },
    { id: 'NYJ-RB3', name: 'Isaiah Davis', position: 'RB', team: 'NYJ' },
    { id: 'NYJ-WR1', name: 'Garrett Wilson', position: 'WR', team: 'NYJ' },
    { id: 'NYJ-WR2', name: 'Adonai Mitchell', position: 'WR', team: 'NYJ' },
    { id: 'NYJ-WR3', name: 'Isaiah Williams', position: 'WR', team: 'NYJ' },
    { id: 'NYJ-WR4', name: 'Arian Smith', position: 'WR', team: 'NYJ' },
    { id: 'NYJ-TE1', name: 'Mason Taylor', position: 'TE', team: 'NYJ' },
    { id: 'NYJ-TE2', name: 'Jeremy Ruckert', position: 'TE', team: 'NYJ' },
    { id: 'NYJ-K1', name: 'Jason Sanders', position: 'K', team: 'NYJ' },
    { id: 'NYJ-DEF', name: 'New York Jets Defense', position: 'DEF', team: 'NYJ' },
  ],
  PHI: [
    { id: 'PHI-QB1', name: 'Jalen Hurts', position: 'QB', team: 'PHI' },
    { id: 'PHI-QB2', name: 'Tanner McKee', position: 'QB', team: 'PHI' },
    { id: 'PHI-RB1', name: 'Saquon Barkley', position: 'RB', team: 'PHI' },
    { id: 'PHI-RB2', name: 'Tank Bigsby', position: 'RB', team: 'PHI' },
    { id: 'PHI-RB3', name: 'Will Shipley', position: 'RB', team: 'PHI' },
    { id: 'PHI-WR1', name: 'DeVonta Smith', position: 'WR', team: 'PHI' },
    { id: 'PHI-WR2', name: 'Makai Lemon', position: 'WR', team: 'PHI' },
    { id: 'PHI-WR3', name: 'Dontayvion Wicks', position: 'WR', team: 'PHI' },
    { id: 'PHI-WR4', name: 'Hollywood Brown', position: 'WR', team: 'PHI' },
    { id: 'PHI-TE1', name: 'Dallas Goedert', position: 'TE', team: 'PHI' },
    { id: 'PHI-TE2', name: 'Eli Stowers', position: 'TE', team: 'PHI' },
    { id: 'PHI-K1', name: 'Jake Elliott', position: 'K', team: 'PHI' },
    { id: 'PHI-DEF', name: 'Philadelphia Eagles Defense', position: 'DEF', team: 'PHI' },
  ],
  PIT: [
    { id: 'PIT-QB1', name: 'Aaron Rodgers', position: 'QB', team: 'PIT' },
    { id: 'PIT-QB2', name: 'Mason Rudolph', position: 'QB', team: 'PIT' },
    { id: 'PIT-RB1', name: 'Jaylen Warren', position: 'RB', team: 'PIT' },
    { id: 'PIT-RB2', name: 'Rico Dowdle', position: 'RB', team: 'PIT' },
    { id: 'PIT-RB3', name: 'Kaleb Johnson', position: 'RB', team: 'PIT' },
    { id: 'PIT-WR1', name: 'DK Metcalf', position: 'WR', team: 'PIT' },
    { id: 'PIT-WR2', name: 'Michael Pittman Jr.', position: 'WR', team: 'PIT' },
    { id: 'PIT-WR3', name: 'Roman Wilson', position: 'WR', team: 'PIT' },
    { id: 'PIT-WR4', name: 'Germie Bernard', position: 'WR', team: 'PIT' },
    { id: 'PIT-TE1', name: 'Pat Freiermuth', position: 'TE', team: 'PIT' },
    { id: 'PIT-TE2', name: 'Darnell Washington', position: 'TE', team: 'PIT' },
    { id: 'PIT-K1', name: 'Chris Boswell', position: 'K', team: 'PIT' },
    { id: 'PIT-DEF', name: 'Pittsburgh Steelers Defense', position: 'DEF', team: 'PIT' },
  ],
  SEA: [
    { id: 'SEA-QB1', name: 'Sam Darnold', position: 'QB', team: 'SEA' },
    { id: 'SEA-QB2', name: 'Drew Lock', position: 'QB', team: 'SEA' },
    { id: 'SEA-RB1', name: 'Zach Charbonnet', position: 'RB', team: 'SEA' },
    { id: 'SEA-RB2', name: 'Jadarian Price', position: 'RB', team: 'SEA' },
    { id: 'SEA-RB3', name: 'George Holani', position: 'RB', team: 'SEA' },
    { id: 'SEA-WR1', name: 'Jaxon Smith-Njigba', position: 'WR', team: 'SEA' },
    { id: 'SEA-WR2', name: 'Rashid Shaheed', position: 'WR', team: 'SEA' },
    { id: 'SEA-WR3', name: 'Cooper Kupp', position: 'WR', team: 'SEA' },
    { id: 'SEA-WR4', name: 'Tory Horton', position: 'WR', team: 'SEA' },
    { id: 'SEA-TE1', name: 'AJ Barner', position: 'TE', team: 'SEA' },
    { id: 'SEA-TE2', name: 'Eric Saubert', position: 'TE', team: 'SEA' },
    { id: 'SEA-K1', name: 'Jason Myers', position: 'K', team: 'SEA' },
    { id: 'SEA-DEF', name: 'Seattle Seahawks Defense', position: 'DEF', team: 'SEA' },
  ],
  SF: [
    { id: 'SF-QB1', name: 'Brock Purdy', position: 'QB', team: 'SF' },
    { id: 'SF-QB2', name: 'Mac Jones', position: 'QB', team: 'SF' },
    { id: 'SF-RB1', name: 'Christian McCaffrey', position: 'RB', team: 'SF' },
    { id: 'SF-RB2', name: 'Jordan James', position: 'RB', team: 'SF' },
    { id: 'SF-RB3', name: 'Kaelon Black', position: 'RB', team: 'SF' },
    { id: 'SF-WR1', name: 'Mike Evans', position: 'WR', team: 'SF' },
    { id: 'SF-WR2', name: 'Deebo Samuel Sr.', position: 'WR', team: 'SF' },
    { id: 'SF-WR3', name: "De'Zhaun Stribling", position: 'WR', team: 'SF' },
    { id: 'SF-WR4', name: 'Christian Kirk', position: 'WR', team: 'SF' },
    { id: 'SF-TE1', name: 'George Kittle', position: 'TE', team: 'SF' },
    { id: 'SF-TE2', name: 'Jake Tonges', position: 'TE', team: 'SF' },
    { id: 'SF-K1', name: 'Eddy Pineiro', position: 'K', team: 'SF' },
    { id: 'SF-DEF', name: 'San Francisco 49ers Defense', position: 'DEF', team: 'SF' },
  ],
  TB: [
    { id: 'TB-QB1', name: 'Baker Mayfield', position: 'QB', team: 'TB' },
    { id: 'TB-QB2', name: 'Jake Browning', position: 'QB', team: 'TB' },
    { id: 'TB-RB1', name: 'Bucky Irving', position: 'RB', team: 'TB' },
    { id: 'TB-RB2', name: 'Kenny Gainwell', position: 'RB', team: 'TB' },
    { id: 'TB-RB3', name: 'Sean Tucker', position: 'RB', team: 'TB' },
    { id: 'TB-WR1', name: 'Emeka Egbuka', position: 'WR', team: 'TB' },
    { id: 'TB-WR2', name: 'Chris Godwin Jr.', position: 'WR', team: 'TB' },
    { id: 'TB-WR3', name: 'Jalen McMillan', position: 'WR', team: 'TB' },
    { id: 'TB-WR4', name: 'Tez Johnson', position: 'WR', team: 'TB' },
    { id: 'TB-TE1', name: 'Cade Otton', position: 'TE', team: 'TB' },
    { id: 'TB-TE2', name: 'Payne Durham', position: 'TE', team: 'TB' },
    { id: 'TB-K1', name: 'Chase McLaughlin', position: 'K', team: 'TB' },
    { id: 'TB-DEF', name: 'Tampa Bay Buccaneers Defense', position: 'DEF', team: 'TB' },
  ],
  TEN: [
    { id: 'TEN-QB1', name: 'Cam Ward', position: 'QB', team: 'TEN' },
    { id: 'TEN-QB2', name: 'Mitchell Trubisky', position: 'QB', team: 'TEN' },
    { id: 'TEN-RB1', name: 'Tony Pollard', position: 'RB', team: 'TEN' },
    { id: 'TEN-RB2', name: 'Tyjae Spears', position: 'RB', team: 'TEN' },
    { id: 'TEN-RB3', name: 'Nicholas Singleton', position: 'RB', team: 'TEN' },
    { id: 'TEN-WR1', name: 'Calvin Ridley', position: 'WR', team: 'TEN' },
    { id: 'TEN-WR2', name: "Wan'Dale Robinson", position: 'WR', team: 'TEN' },
    { id: 'TEN-WR3', name: 'Carnell Tate', position: 'WR', team: 'TEN' },
    { id: 'TEN-WR4', name: 'Elic Ayomanor', position: 'WR', team: 'TEN' },
    { id: 'TEN-TE1', name: 'Gunnar Helm', position: 'TE', team: 'TEN' },
    { id: 'TEN-TE2', name: 'Daniel Bellinger', position: 'TE', team: 'TEN' },
    { id: 'TEN-K1', name: 'Joey Slye', position: 'K', team: 'TEN' },
    { id: 'TEN-DEF', name: 'Tennessee Titans Defense', position: 'DEF', team: 'TEN' },
  ],
  WAS: [
    { id: 'WAS-QB1', name: 'Jayden Daniels', position: 'QB', team: 'WAS' },
    { id: 'WAS-QB2', name: 'Marcus Mariota', position: 'QB', team: 'WAS' },
    { id: 'WAS-RB1', name: 'Jacory Croskey-Merritt', position: 'RB', team: 'WAS' },
    { id: 'WAS-RB2', name: 'Rachaad White', position: 'RB', team: 'WAS' },
    { id: 'WAS-RB3', name: 'Kaytron Allen', position: 'RB', team: 'WAS' },
    { id: 'WAS-WR1', name: 'Terry McLaurin', position: 'WR', team: 'WAS' },
    { id: 'WAS-WR2', name: 'Stefon Diggs', position: 'WR', team: 'WAS' },
    { id: 'WAS-WR3', name: 'Treylon Burks', position: 'WR', team: 'WAS' },
    { id: 'WAS-WR4', name: 'Van Jefferson', position: 'WR', team: 'WAS' },
    { id: 'WAS-TE1', name: 'Chig Okonkwo', position: 'TE', team: 'WAS' },
    { id: 'WAS-TE2', name: 'John Bates', position: 'TE', team: 'WAS' },
    { id: 'WAS-K1', name: 'Drew Stevens', position: 'K', team: 'WAS' },
    { id: 'WAS-DEF', name: 'Washington Commanders Defense', position: 'DEF', team: 'WAS' },
  ],
};

export function getDefaultPlayers(): Player[] {
  return Object.values(NFL_PLAYERS_BY_TEAM)
    .flat()
    .map(p => ({ ...p, isDrafted: false }));
}
